# Generated by Django 5.0.6 on 2024-06-22 20:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publicaiones',
            new_name='Publicaciones',
        ),
    ]
