# Generated by Django 5.0.6 on 2024-06-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_publicaiones_publicaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicaciones',
            old_name='descrpcion',
            new_name='descripcion',
        ),
    ]
