# Generated by Django 5.0.6 on 2024-07-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_descrpcion_publicaciones_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
